name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build JAR
        run: |
          ./gradlew clean bootjar
          ls -al ./build/libs
          date

      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostkeyChecking=no -i private_key.pem ./build/libs/BoardProject-0.0.1-SNAPSHOT.jar ubuntu@13.49.243.30:/home/ubuntu/spring/boardproject.jar

      - name: Copy Dockerfile to EC2
        run: |
          scp -o StrictHostkeyChecking=no -i private_key.pem ./Dockerfile ubuntu@13.49.243.30:/home/ubuntu/spring/

      - name: Deploy to EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~/spring
            git pull origin main
            sudo docker ps
            sudo docker ps -al
            sudo docker build --no-cache -t boardproject .
            sudo docker stop boardproject || true
            sudo docker rm boardproject || true
            sudo docker rmi boardproject || true
            sudo docker build -t boardproject .
            sudo docker run -d -p 8080:8080 --name boardproject boardproject
            sudo docker ps
            sudo docker ps -al
          EOF
