name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2 and run Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ~/spring
            git pull origin main
            sudo docker stop board || true
            sudo docker rm board || true
            sudo docker rmi boardproject || true
            sudo docker build -t boardproject .
            sudo docker run -d -p 8080:8080 --name board boardproject
          EOF
